"""initial_schema

Revision ID: 2db850b82f15
Revises: 
Create Date: 2026-03-24 23:25:28.854541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db850b82f15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('detected_languages', sa.Text(), nullable=True),
    sa.Column('detected_frameworks', sa.Text(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_symbols', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_url')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=True)
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_index(op.f('ix_repositories_status'), 'repositories', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('delivery_id', sa.String(length=255), nullable=True),
    sa.Column('repository_url', sa.String(length=1024), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', name='uq_webhook_events_delivery_id')
    )
    op.create_index(op.f('ix_webhook_events_delivery_id'), 'webhook_events', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_repository_url'), 'webhook_events', ['repository_url'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latest_commit_sha', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_repository_id'), 'branches', ['repository_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_repository_id'), 'chat_sessions', ['repository_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('file_kind', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('is_config', sa.Boolean(), nullable=False),
    sa.Column('is_doc', sa.Boolean(), nullable=False),
    sa.Column('is_vendor', sa.Boolean(), nullable=False),
    sa.Column('parse_status', sa.String(length=50), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_file_kind'), 'files', ['file_kind'], unique=False)
    op.create_index(op.f('ix_files_language'), 'files', ['language'], unique=False)
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=False)
    op.create_index(op.f('ix_files_repository_id'), 'files', ['repository_id'], unique=False)
    op.create_table('github_installations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_installations_installation_id'), 'github_installations', ['installation_id'], unique=False)
    op.create_index(op.f('ix_github_installations_repository_id'), 'github_installations', ['repository_id'], unique=False)
    op.create_table('onboarding_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('generation_mode', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_documents_repository_id'), 'onboarding_documents', ['repository_id'], unique=False)
    op.create_table('pr_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('blast_radius', sa.Text(), nullable=True),
    sa.Column('suggested_reviewers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_analyses_repository_id'), 'pr_analyses', ['repository_id'], unique=False)
    op.create_table('repo_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_jobs_job_type'), 'repo_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_repo_jobs_repository_id'), 'repo_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repo_jobs_status'), 'repo_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_repo_jobs_task_id'), 'repo_jobs', ['task_id'], unique=False)
    op.create_table('repo_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_snapshots_repository_id'), 'repo_snapshots', ['repository_id'], unique=False)
    op.create_table('repository_refresh_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_files_json', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_refresh_jobs_repository_id'), 'repository_refresh_jobs', ['repository_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('dependency_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=True),
    sa.Column('target_file_id', sa.String(length=36), nullable=True),
    sa.Column('edge_type', sa.String(length=100), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('target_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_edges_edge_type'), 'dependency_edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_dependency_edges_repository_id'), 'dependency_edges', ['repository_id'], unique=False)
    op.create_table('embedding_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('embedding_vector', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_chunks_chunk_type'), 'embedding_chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_embedding_chunks_file_id'), 'embedding_chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_embedding_chunks_repository_id'), 'embedding_chunks', ['repository_id'], unique=False)
    op.create_table('risk_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_metrics_metric_type'), 'risk_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_risk_metrics_repository_id'), 'risk_metrics', ['repository_id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol_type', sa.String(length=100), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_file_id'), 'symbols', ['file_id'], unique=False)
    op.create_index(op.f('ix_symbols_name'), 'symbols', ['name'], unique=False)
    op.create_index(op.f('ix_symbols_repository_id'), 'symbols', ['repository_id'], unique=False)
    op.create_index(op.f('ix_symbols_symbol_type'), 'symbols', ['symbol_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbols_symbol_type'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_repository_id'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_name'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_file_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_risk_metrics_repository_id'), table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_metric_type'), table_name='risk_metrics')
    op.drop_table('risk_metrics')
    op.drop_index(op.f('ix_embedding_chunks_repository_id'), table_name='embedding_chunks')
    op.drop_index(op.f('ix_embedding_chunks_file_id'), table_name='embedding_chunks')
    op.drop_index(op.f('ix_embedding_chunks_chunk_type'), table_name='embedding_chunks')
    op.drop_table('embedding_chunks')
    op.drop_index(op.f('ix_dependency_edges_repository_id'), table_name='dependency_edges')
    op.drop_index(op.f('ix_dependency_edges_edge_type'), table_name='dependency_edges')
    op.drop_table('dependency_edges')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_repository_refresh_jobs_repository_id'), table_name='repository_refresh_jobs')
    op.drop_table('repository_refresh_jobs')
    op.drop_index(op.f('ix_repo_snapshots_repository_id'), table_name='repo_snapshots')
    op.drop_table('repo_snapshots')
    op.drop_index(op.f('ix_repo_jobs_task_id'), table_name='repo_jobs')
    op.drop_index(op.f('ix_repo_jobs_status'), table_name='repo_jobs')
    op.drop_index(op.f('ix_repo_jobs_repository_id'), table_name='repo_jobs')
    op.drop_index(op.f('ix_repo_jobs_job_type'), table_name='repo_jobs')
    op.drop_table('repo_jobs')
    op.drop_index(op.f('ix_pr_analyses_repository_id'), table_name='pr_analyses')
    op.drop_table('pr_analyses')
    op.drop_index(op.f('ix_onboarding_documents_repository_id'), table_name='onboarding_documents')
    op.drop_table('onboarding_documents')
    op.drop_index(op.f('ix_github_installations_repository_id'), table_name='github_installations')
    op.drop_index(op.f('ix_github_installations_installation_id'), table_name='github_installations')
    op.drop_table('github_installations')
    op.drop_index(op.f('ix_files_repository_id'), table_name='files')
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.drop_index(op.f('ix_files_language'), table_name='files')
    op.drop_index(op.f('ix_files_file_kind'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_chat_sessions_repository_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_branches_repository_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_webhook_events_repository_url'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_delivery_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repositories_status'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
