"""add_repo_intelligence_and_file_enrichment

Revision ID: a0a725601d8a
Revises: 2db850b82f15
Create Date: 2026-03-30 15:20:48.974366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0a725601d8a'
down_revision: Union[str, None] = '2db850b82f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_summaries_file_id', table_name='file_summaries')
    op.drop_index('ix_file_summaries_path', table_name='file_summaries')
    op.drop_index('ix_file_summaries_repository_id', table_name='file_summaries')
    op.drop_table('file_summaries')
    op.drop_index('ix_repo_memory_repository_id', table_name='repo_memory')
    op.drop_table('repo_memory')
    op.drop_index('ix_embedding_chunks_symbol_name', table_name='embedding_chunks')
    op.drop_column('embedding_chunks', 'symbol_name')
    op.add_column('files', sa.Column('summary_text', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('imports_list', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('exports_list', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('framework_hints', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('importance_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'importance_score')
    op.drop_column('files', 'framework_hints')
    op.drop_column('files', 'exports_list')
    op.drop_column('files', 'imports_list')
    op.drop_column('files', 'responsibilities')
    op.drop_column('files', 'summary_text')
    op.add_column('embedding_chunks', sa.Column('symbol_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_embedding_chunks_symbol_name', 'embedding_chunks', ['symbol_name'], unique=False)
    op.create_table('repo_memory',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('repository_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('primary_language', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('frameworks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('top_level_dirs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entrypoints', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('detected_services', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('backend_paths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('frontend_paths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('api_routes_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('db_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auth_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deployment_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('build_tools', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('test_frameworks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_files', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('repo_summary_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('architecture_summary_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingestion_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_source_files', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_ignored_files', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name='repo_memory_repository_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='repo_memory_pkey')
    )
    op.create_index('ix_repo_memory_repository_id', 'repo_memory', ['repository_id'], unique=True)
    op.create_table('file_summaries',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('repository_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('line_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_kind', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responsibilities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imports_list', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exports_list', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('classes_list', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('functions_list', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('route_defs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('db_models', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config_keys', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('framework_hints', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inbound_deps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('outbound_deps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('symbol_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('importance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_entrypoint', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name='file_summaries_file_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name='file_summaries_repository_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='file_summaries_pkey')
    )
    op.create_index('ix_file_summaries_repository_id', 'file_summaries', ['repository_id'], unique=False)
    op.create_index('ix_file_summaries_path', 'file_summaries', ['path'], unique=False)
    op.create_index('ix_file_summaries_file_id', 'file_summaries', ['file_id'], unique=True)
    # ### end Alembic commands ###
